name: Baby-triton-test
env:
  TVM-HOME: ${github.workspace}/tvm
  PYTHONPATH: $TVM_HOME/python:${PYTHONPATH}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *' # Runs at 11pm everyday
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout LLVM
      uses: actions/checkout@v3

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: Install Other needed packages # maybe install llvm release is a better choice
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 16
        sudo apt-get install -y \
        python3 python3-dev python3-venv \

    - name: Start building tvm
      shell: bash
      run: |
        git submodule update --recursive
        cd tvm
        bash build-linux.sh
